### ISSUE TITLE
When will the dataset be published

### ISSUE THREAD

**Issue by wuwuwuyue** [YZY-stack/DF40#1]
Hello, our laboratory is very interested in the DF40 dataset. We would like to know when the dataset will be open. If it is still a long time before the entire dataset is published, could you first publish the test set of the dataset for us to measure the performance of our detector on your dataset.

**Comment by YZY-stack** [comment]
@wuwuwuyue
Thank you very much for your attention to this matter. We will promptly proceed with the legal review of copyright issues and the compilation of datasets. Our goal is to provide a highly convenient version, seamlessly compatible with DeepfakeBench, as soon as possible.

**Comment by wuwuwuyue** [comment]
Can you provide the test set in advance? We will comply with all the rules you  proposed

**Comment by YZY-stack** [comment]
Hi @wuwuwuyue , we have released the DF40 dataset on our GitHub page. Thanks for your attention!
