### ISSUE TITLE
Question! Missing python files.

### ISSUE THREAD

**Issue by minmini2** [YZY-stack/DF40#12]
Hello,
Thank you for sharing the impressive paper, dataset, and checkpoints.

While running the code, I noticed that some files seem to be missing, such as dataset.FWABlendDataset, detectors.facexray_detector, and detectors.xception_detector under the datasets directory. Could you kindly let me know where I can find these files?

**Comment by YZY-stack** [comment]
Thanks for your kind mention! 

The codebase is developed based on DeepfakeBench. The mentioned Python files are implemented inside the DeepfakeBench, but in DF40, we do not implement these detectors and datasets. I have deleted them in [__init__.py](https://github.com/YZY-stack/DF40/blob/main/DeepfakeBench_DF40/training/detectors/__init__.py)

**Comment by minmini2** [comment]
Thank you for your reply! :)

I will apply the changes you mentioned and check again!

**Comment by minmini2** [comment]
I have an additional question.

I downloaded the DF40 dataset and would like to train the model using the DF40 data. The command I am using is as follows:

**python3 -m torch.distributed.launch --nproc_per_node=8 training/train.py --detector_path ./training/config/detector/xception.yaml --test_dataset "EFSAll_ff" --train_dataset "DF40_all" --ddp**

However, in the provided DF40_all.json file, there is no precise information regarding the image frame paths. For example, the paths are listed like this:

**deepfakes_detection_datasets/DF40/{}/{},
deepfakes_detection_datasets/DF40_train/{}/{}**

But the paths provided in Google Cloud do not follow this format. I tried to match them as closely as possible, but I am still encountering errors such as:

**MidJourney_Fake_13592447708_Caucasian_male_face_face_only_shown_face_close-up_f_3bb03f4c-eefd-49f6-92c5-a37e78e3ade1 is None. Let's skip it.**

Could you please provide the correct steps or instructions for training the model?

**Comment by YZY-stack** [comment]
Hi, sorry for the confusion. I have re-uploaded the JSON files and clarify the fold structure in the README.md file

Specifically, please check:

1. JSON-file: [link](https://drive.google.com/drive/folders/1rh-82Rn0pqQ7xzLDKBv9gdjy-sbxYC8-)
2. Folder-structure, please refer to the latest README.md for details.

![image](https://github.com/user-attachments/assets/3f3d4ba7-969e-4700-a624-ebeeeca7cc93)
