### ISSUE TITLE
Confused by the organization of the dataset provided in google drive

### ISSUE THREAD

**Issue by JoeLeelyf** [YZY-stack/DF40#17]
I noticed their are several duplicated zip files in the google drive folder, like "sd2.1_new.zip" and "sd_2.1.zip", and their content vary a lot.
![Screenshot 2024-10-23 at 19 35 14](https://github.com/user-attachments/assets/76e7a065-5b26-43ef-ac4c-8494356b8d2b)
And I have also noticed that the content provided in Google drive and baidu netdisk may differ.
![Screenshot 2024-10-23 at 19 39 50](https://github.com/user-attachments/assets/04a2e69e-541b-4d19-bd8d-d8d066f070eb)

**Comment by YZY-stack** [comment]
Hello, I have reorganized the mentioned Google Drive directory. It should be in proper order now. 

If there are still discrepancies between Google and Baidu results, please point them out and let me know. Thank you very much.

**Comment by JoeLeelyf** [comment]
Thanks for your work, but we have also noticed the discrepancy between the file structure in the upload zip files and the annotations in the JSON file.
![Screenshot 2024-10-23 at 21 23 00](https://github.com/user-attachments/assets/e9c50ca0-bd54-4fe5-9f3a-c69bdec3487d)
And as we have previously implied in #16 , it's an urgent need for the refresh of the JSON files you provided.

**Comment by YZY-stack** [comment]
OK. Please let me know: is this the training sd2.1 or testing sd2.1?

And, don't worry. I will fix the issue [#16](https://github.com/YZY-stack/DF40/issues/16) you mentioned tomorrow.

**Comment by JoeLeelyf** [comment]
It's sd2.1 in testing set, and it our glad to see your timely response.

**Comment by JoeLeelyf** [comment]
Additionally, when I unzip the downloaded zip files, I found that it may encounter great trouble if using the "unzip *.zip" linux command directly. Like, when unzip some compressed files, I obtain cdf/ff/__MACOSX folders directly under my current dir, while others would come out with a parent folder like "sd2.1"/"uniface" etc.
It seems that the structure of the zip files varies and can cause troubles. It recommended that you organize the zip files uniformly and provide the exact command to obtain file structure as in your JSON files.

**Comment by JoeLeelyf** [comment]
Check out the MidJourney zip file in the testing set:
In the provided JSON file, the images in MidJourney are placed under real/fake dir respectively,
<img width="592" alt="Screenshot 2024-10-26 at 21 05 36" src="https://github.com/user-attachments/assets/5b9eb5a8-4241-4441-b029-88d5f4c67e04">
However, in the MidJourney.zip, no real images are provided, all files are placed directly under the MidJourney dir.
<img width="531" alt="Screenshot 2024-10-26 at 21 06 47" src="https://github.com/user-attachments/assets/6119bef0-0074-4d76-abff-d7403ae70831">

**Comment by YZY-stack** [comment]
@JoeLeelyf Hi, please check the latest MidJourney version. I have updated it just now. Please refer to this [link](https://drive.google.com/file/d/1K0_sUcVLY4V6g7MF_hCEzoPagIMxdAxh/view?usp=drive_link). Sorry for the confusion.
