### ISSUE TITLE
Midjourney Subset Issue: Missing Real Part and JSON Mismatch

### ISSUE THREAD

**Issue by PhD-TianLv** [YZY-stack/DF40#18]
The Midjourney subset only contains the fake part, missing the real part, and does not correspond with the JSON.
![image](https://github.com/user-attachments/assets/548cae99-c51e-4e39-a798-1acc3cbc63db)
![image](https://github.com/user-attachments/assets/90ece69a-2b86-4973-9bad-9229e157fd3f)

**Comment by YZY-stack** [comment]
Thanks for your kind mention. I have updated this file. Please check the latest version at [here](https://drive.google.com/file/d/1K0_sUcVLY4V6g7MF_hCEzoPagIMxdAxh/view?usp=drive_link).
