### ISSUE TITLE
/df40_videos/test/blendface.zip corrupted.

### ISSUE THREAD

**Issue by wangxianliang** [YZY-stack/DF40#21]
The file is downloaded from https://drive.google.com/drive/folders/1K0N0is62Bbc3OhqGrzN8fgyd8qayOEeE
When decompress /df40_videos/test/blendface.zip, it pops up message:  "unexpected end of compressed file. file may be truncated"

**Comment by yermandy** [comment]
Use `7z x blendface.zip`

**Comment by wangxianliang** [comment]
> Use `7z x blendface.zip`

![image](https://github.com/user-attachments/assets/49122ef4-a718-431e-bfdd-de853c655d70)
Still has error.

**Comment by YZY-stack** [comment]
@wangxianliang I am sorry for the late reply. I have re-uploaded the blendface.zip file. Please check this [link](https://drive.google.com/file/d/1OG4e6CxGEbhwHFdE1biL5lolIiMJEPMB/view?usp=drive_link).
