### ISSUE TITLE
Google Link anomaly ！

### ISSUE THREAD

**Issue by Dongyu-Han** [YZY-stack/DF40#22]
Thank you for sharing the dataset, but I found the Google link you provided too confusing, the training dataset and test dataset links did not match, and the CDF real dataset links non-data.

**Comment by YZY-stack** [comment]
Thanks. We have separated the training data from the testing data, as some people may only wish to use DF40 as the evaluation set without conducting any training on it.

Moreover, we have checked and verified that the link of the CDF real dataset is working fine. If you encounter any issues accessing it, please check your network connection or consider using Baidu Disk instead. Thank you.
