### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by yermandy** [YZY-stack/DF40#23]
Hello, would it be possible to release codes for generating datasets, it would be helpful to have them to have more control over data generation?

**Comment by YZY-stack** [comment]
Hi, we have provided the codes for generating EFS data ([link](https://github.com/YZY-stack/DF40/tree/main/EFS_finetune_code)).

For other generators such FS and FR, please refer to Table 2 of the DF40 paper [(link)](https://arxiv.org/abs/2406.13495), where we have demonstrated the official repos for each generation method.

Additionally, I found that the widely-used *facefusion* [link](https://github.com/facefusion/facefusion) is very easy to use. For FS methods, I highly recommend using *facefusion* for implementation.

**Comment by yermandy** [comment]
This is very helpful! Thank you for sharing links, the facefusion is indeed very good. For other generator methods, did you just use standard implementations of all generators provided by authors?

**Comment by yermandy** [comment]
Thank you and I appreciate your quick responses!
