### ISSUE TITLE
Hi! Which version of FF++ is used for the original data? raw or c23 or c40?

### ISSUE THREAD

**Issue by githuboflk** [YZY-stack/DF40#24]

**Comment by YZY-stack** [comment]
Hi, we use FF++ (c23) for the original data, following the most mainstream protocol: training on FF++ (c23) and testing on CDF. Most of our forgery data (31 methods) are generated within the FF++ (c23) and CDF domains, aiming to seamlessly enlarge this mainstream evaluation protocol.

**Comment by githuboflk** [comment]
> Hi, we use **FF++ (c23)** for the original data, following the most mainstream protocol: training on FF++ (c23) and testing on CDF. Most of our forgery data (31 methods) are generated within the FF++ (c23) and CDF domains, aiming to seamlessly enlarge this mainstream evaluation protocol.
> 
> For instance, for cross-method evaluations, you can train the model on simswap (FF) and test it on blendface (FF); for cross-domain evaluations, you can train the model on simswap (FF) and test it on simswap (CDF). Please refer to Protocol-1 and Protocol-2 in our work for details.

Thanks for the reply! Great work!
