### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Houssem171** [YZY-stack/DF40#6]
The detectors folder is missing **base_detector.py** file that contains the **AbstractDetector()** class.

**Comment by beautyremain** [comment]
Hello, you can find AbstractDetector() from here: https://github.com/SCLBD/DeepfakeBench/blob/main/training/detectors/base_detector.py
It should be able to be used directly.

**Comment by Houssem171** [comment]
@beautyremain Yes, that's exactly what I did and it worked just fine. I am just pointing it out for the owner to fix it.

**Comment by YZY-stack** [comment]
Thanks for your kind mention. I have added the `base_detector.py` file inside the "training/detectors/" folder.
